name: Misc Validators
version: 1.0
description: Various additional field validations
url: https://github.com/edalzell/statamic-misc-validators
developer: Erin Dalzell
developer_url: https://thedalzells.org
